-- ============================================================
-- 取数 SQL 模板 (由 cashjy_feature_sql_generator.ipynb 生成)
-- 特征集: ng_pdl1st_cashjy_train_pct95
-- 数据集: ng_pdl1st_cashjy_train
-- 主表: sample_table (请按实际主表核对)  别名: t
-- 关联键: t.pt_sub1d = tN.pt AND t.cid = tN.cid
-- 分区占位: ${pt_beg} ~ ${pt_end}
-- 唯一变量数: 593 个
-- 总共获取的特征字段数: 598 个 (含多来源变量版本列，不含主表基础列)
-- 涉及源表: 12 张
-- 告警数: 9 条，请结合 generated_feature_warnings.csv 人工核对
-- 每个来源表获取的字段数统计:
-- t1: pb_ads_credit.direct_send_in_out_para_data_df -> 获取 255 个特征字段
-- t2: pb_biz_credit.keep_jch_ng_cid_repay_feature_final -> 获取 24 个特征字段
-- t3: pb_biz_credit.keep_jch_ng_cid_bal_feature_final -> 获取 23 个特征字段
-- t4: pb_ads_credit.ads_ng_risk_pp_cid_character_360d -> 获取 181 个特征字段
-- t5: pb_biz_credit.ng_customer_pay_plan_flow_feas -> 获取 19 个特征字段
-- t6: pb_biz_credit.keep_jch_ng_cid_util_feature_final -> 获取 22 个特征字段
-- t7: pb_biz_credit.keep_jch_ng_cid_apply_feature_final -> 获取 9 个特征字段
-- t8: pb_biz_credit.keep_ng_jch_cid_overdue_feature_final -> 获取 16 个特征字段
-- t9: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final -> 获取 7 个特征字段
-- t10: pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature -> 获取 4 个特征字段
-- t11: pb_biz_credit.ng_pp_user_financial_feature_profile_di -> 获取 33 个特征字段
-- t12: pb_biz_credit.keep_jch_ng_cid_tenor_feature_final -> 获取 5 个特征字段
-- 告警分类: same_variable_multiple_sources=5, same_row_multiple_sources=4
-- [!] 变量 bank_cnt_90d: 同一 Excel 行包含多个来源表，默认全部保留; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 top1_inst_query_ratio_180d: 同一 Excel 行包含多个来源表，默认全部保留; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 blacklist_cnt_180d: 同一 Excel 行包含多个来源表，默认全部保留; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 bank_cnt_180d: 同一 Excel 行包含多个来源表，默认全部保留; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 payer_repay_cnt_360d_v2: 同一变量来自多张来源表，已按出现顺序生成版本别名，请人工核对口径; 来源: pb_ads_credit.direct_send_in_out_para_data_df, pb_ads_credit.ads_ng_risk_pp_cid_character_360d
-- [!] 变量 bank_cnt_90d: 同一变量来自多张来源表，已按出现顺序生成版本别名，请人工核对口径; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 top1_inst_query_ratio_180d: 同一变量来自多张来源表，已按出现顺序生成版本别名，请人工核对口径; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 blacklist_cnt_180d: 同一变量来自多张来源表，已按出现顺序生成版本别名，请人工核对口径; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- [!] 变量 bank_cnt_180d: 同一变量来自多张来源表，已按出现顺序生成版本别名，请人工核对口径; 来源: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final, pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
-- ============================================================
select
    t.businessid,
    t.jy_date,
    t.fpd10_fz_dd,
    t1.loan_total_fee,
    t1.loan_total_interest,
    t1.loan_interest_days,
    t2.max_paid_interest_180d_t79,
    t3.press_180d_all,
    t1.latitude,
    t1.app_version,
    t4.payer_amount_median_60d_v2,
    t1.age,
    t3.press_90d_all,
    t1.loan_interest_rate,
    t1.user_withdrawal_ratio_now,
    t1.reg_day,
    t1.n_loan_period_days,
    t1.usr_overdue_days_max,
    t1.ng_pp_total_balance_off,
    t1.pp_max_nibssfund_amt_3d,
    t1.max_trans_amt_1m,
    t1.cust_curr_overdue_bill_amt,
    t1.c_first_3dig_bvn,
    t1.pp_payoff_cnt,
    t4.loan_net_inflow_90d_v2,
    t4.loan_net_inflow_60d_v2,
    t1.other_self_airtime_cnts,
    t1.bus_pp_30d_aum,
    t1.loan_penalty_rate,
    t1.one_period_days,
    t5.last_initiative_pay_days,
    t1.ng_ins_increase_currd_total_amt,
    t2.deduct_ratio_due_180d_t79,
    t1.cash_cur_day_ser_increase_cnt,
    t1.loan_cust_account_status,
    t6.cv_util_180d_all,
    t1.pp_trans_amt_7d,
    t1.pp_register_software,
    t7.days_since_registration,
    t1.avg_balance_when_gt_0_90d,
    t1.max_trans_amt_6m,
    t1.available_balance_pp,
    t4.payer_amount_median_15d_v2,
    t5.first_initiative_pay_days,
    t1.pp_nibssfund_amt_3d,
    t1.payer_repay_cnt_360d_v2,
    t1.num_device_count,
    t1.ng_same_nin_max_cur_overdue_day_cash_rt,
    t3.press_15d_t9,
    t1.total_storage,
    t4.payee_txn_per_day_360d_v2,
    t3.press_prev90d_all,
    t5.last_pay_days,
    t8.max_od_days_180d_79,
    t1.ng_cash_success_loan_cnt_d3,
    t1.transfer_cnt_1m,
    t1.databundle_airtime_amt_1m,
    t1.ng_cash_settle_ratio,
    t6.last_util_1_all,
    t1.trans_days_60d,
    t4.payee_unique_payer_count_7d_v2,
    t1.if_register_palmpay_device,
    t6.util_180d_sumratio_all,
    t1.ng_cash_withdraw_jy_reject_cnt,
    t1.cash_days_from_last_incresed,
    t1.ng_applist_pkgname_last_30_day_pd3_best5_cnt,
    t3.press_60d_all,
    t1.ng_cash_success_loan_cnt_d14,
    t1.max_authen_days,
    t1.p20_total_finsave_amt_d30,
    t1.total_vat_7d,
    t1.n_cust_max_overdue_days,
    t1.ins_max_cur_overdue_day_for_loan,
    t1.ng_cash_loan_cnt_7d,
    t9.bank_cnt_90d,
    t10.bank_cnt_90d as bank_cnt_90d_v1,
    t1.pp_last_reg_days,
    t1.hours_since_last_launch,
    t1.other_airtime_cnt,
    t1.cust_last_market_increase_days,
    t1.pp_trans_days_14d,
    t1.phone_model,
    t1.ratio_install_90d,
    t1.ng_ins_reg_sx_days,
    t1.min_authen_days,
    t1.pc_counter_sx_curday_succ_cnt,
    t1.ng_collect_cuiji_ptp_times_30d,
    t4.payer_txn_per_day_360d_v2,
    t4.payer_low_mcht_amt_share_360d_v2,
    t1.ng_total_loyalty_cnt_rate,
    t8.last_overdue_gap_to_asof_days_79,
    t1.total_memory,
    t1.transfer_cnt_3m,
    t1.c_gender,
    t4.payee_txn_per_day_180d_v2,
    t8.max_od_days_30d_79,
    t4.payee_recent_180_amount_share_15d_v2,
    t1.installment_loan_rank,
    t1.self_airtime_vat,
    t1.ng_appname_opay_dd,
    t6.avg_util_180d_all,
    t6.min_util_180d_all,
    t8.max_od_days_90d_79,
    t1.ng_loan_continue_reject_cnt3,
    t1.max_continue_days,
    t1.ng_max_trans_amt,
    t4.fail_txn_ratio_360d_v2,
    t2.max_paid_interest_90d_ratio_prev_t79,
    t1.self_airtime_vat_60d,
    t1.pp_register_second_channel,
    t1.app38_install_days,
    t1.total_daily_vat_14d,
    t1.trans_days_cnt,
    t1.max_verify_days,
    t4.payer_success_rate_60d_v2,
    t3.press_over_quota_180d_all,
    t8.last1_od_days_79,
    t1.coupon_amt,
    t4.payee_recent_360_txn_share_7d_v2,
    t11.ratio_balance_cashbox_all,
    t1.ng_pp_regular_trans_order_cnt_60d_off,
    t1.okcard_last3_max_overdue_days,
    t1.user_recent_overdue_day,
    t4.payee_recent_180_payer_share_30d_v2,
    t1.pp_trans_amt_3d,
    t1.ng_applist_small_1000_b_ratio10_90_days_update_sum_rt,
    t1.app55_install_days,
    t1.inst_cnt_30d,
    t3.press_180d_t7,
    t1.payer_repay_cnt_30d,
    t3.press_30d_t9,
    t4.payee_low_mcht_amt_share_360d_v2,
    t1.databundle_amt_3m,
    t7.days_since_last_apply_type9,
    t4.fail_txn_ratio_90d_v2,
    t1.ng_applist_pkgname_last_30_day_pd3_worst5_cnt,
    t4.payee_fail_rate_360d_v2,
    t4.payer_unique_payee_count_180d_v2,
    t4.payee_avg_txn_per_payer_360d_v2,
    t4.payee_high_mcht_amt_share_360d_v2,
    t3.press_180d_t9,
    t11.sum_balance_cashbox,
    t4.transfer_fail_ratio_360d_v2,
    t7.days_since_first_apply_all,
    t4.payee_amount_cv_360d_v2,
    t9.top1_inst_query_ratio_180d,
    t10.top1_inst_query_ratio_180d as top1_inst_query_ratio_180d_v1,
    t4.payee_unique_hours_active_7d_v2,
    t1.credit_day,
    t1.nibssfund_cnt_7d,
    t2.repay_ratio_due_60d_t79,
    t1.sdcard_used_capacity_rate,
    t1.pp_kyc_profession,
    t4.payer_recent_180_amount_share_90d_v2,
    t1.total_balance_pay_amt_rate,
    t4.payee_recent_360_payer_share_7d_v2,
    t1.same_device_info_differ_regmobile_last30_cnt_plampay,
    t7.days_since_last_apply_all,
    t4.payee_unique_hours_active_15d_v2,
    t1.cus_all_product_curr_overdue_cnt,
    t4.short_cycle_inflow_ratio_t1_v2,
    t8.max_od_days_60d_79,
    t3.press_90d_t7,
    t3.press_7d_all,
    t1.ng_same_bvn_max_cur_overdue_day_cash_rt,
    t6.util_90d_sumratio_all,
    t4.payee_unique_payer_count_360d_v2,
    t1.ng_td_witld_amt_in_bi_rt,
    t1.cust_last2_overdue_days,
    t1.trans_cnt,
    t1.ng_pdl_is_first_order,
    t1.ng_la3times_quota_use_ratio_cash_avg_rt,
    t1.withdraw_apply_total_cnt,
    t1.cust_tier,
    t1.min_pass_verify_days,
    t5.first_pay_days,
    t1.n_cust_last1_overdue_days,
    t1.ng_same_ipaddress_card_cnt_cash_rt,
    t4.payee_avg_txn_per_payer_shift_7d_vs_360d_v2,
    t1.same_device_info_differ_regmobile_total_cnt_plampay,
    t2.early_ratio_due_180d_t79,
    t7.days_since_first_apply_type9,
    t1.ng_cash_total_duedate_repay_cnt_rt,
    t11.diff_balance_all_15days,
    t1.ng_faceid_max_overdue_days_emi,
    t4.payee_txn_per_day_15d_v2,
    t7.days_since_last_apply_type7,
    t2.avg_diff_days_180d_t79,
    t3.press_over_quota_90d_all,
    t4.payer_start_of_month_amount_ratio_360d_v2,
    t1.p80_total_finsave_amt_d90,
    t6.max_util_7d_all,
    t4.payer_recent_360_txn_share_7d_v2,
    t4.fail_txn_ratio_15d_v2,
    t7.concat_last_most_type_30d,
    t1.pay_100up_cnt,
    t4.payee_success_rate_180d_v2,
    t4.payer_unique_payee_count_60d_v2,
    t1.num_connect_user_device,
    t1.num_device_log_7day,
    t1.phone_system,
    t4.payer_repay_cnt_15d_v2,
    t4.payee_start_of_month_amount_ratio_30d_v2,
    t1.ng_applist_small_1000_b_ratio10_30_days_update_sum_rt,
    t1.approval_result1,
    t8.last3_od_days_79,
    t4.payee_recent_180_payer_share_15d_v2,
    t1.pp_nibssfund_days_3d,
    t4.payer_recent_180_amount_share_7d_v2,
    t1.total_performing_facility_ratio,
    t1.p50_balance_amt_d30,
    t1.phone_width,
    t1.bus_application_gps_address_detail,
    t1.total_daily_vam_3d,
    t6.cv_util_30d_all,
    t9.bvn_cnt_15d_div_90d,
    t4.payer_unique_payee_count_360d_v2,
    t1.same_bvn_curr_overdue_days,
    t8.last2_od_days_79,
    t1.trans_amt_3d,
    t5.dpd_due365d_dpd2_bad_due_rt,
    t1.same_device_info_differ_regmobile_last30_cnt,
    t5.dpd_due365d_dpd4_bad_due_rt,
    t6.min_util_7d_all,
    t4.payee_eom_amount_ratio_30d_v2,
    t1.betting_customer_id_pp_count,
    t5.dpd_due365d_dpd8_bad_eli_rt,
    t1.ng_nin_age_rt,
    t1.used_memory,
    t1.max_continue_days_6m,
    t11.diff_balance_all_30days,
    t4.payer_repay_cnt_180d_v2,
    t4.payer_amount_cv_360d_v2,
    t1.stragety_flag_ser,
    t4.payer_repay_cnt_30d_v2,
    t1.ng_pp_regular_trans_order_cnt_3d_off,
    t4.payer_low_mcht_amt_share_30d_v2,
    t3.ratio_press_cur30_prev30_all,
    t4.payee_recent_180_payer_share_90d_v2,
    t1.card_pay_days,
    t2.repay_ratio_due_180d_t79,
    t4.payee_recent_180_payer_share_60d_v2,
    t1.cash_jy_curr_day_cnt,
    t4.payee_amount_cv_90d_v2,
    t1.ng_la360ds_bi_overdue_ds_cash_avg_off,
    t1.flag_offline_limit_adjust,
    t1.wifi_conneted,
    t1.ng_collect_cuiji_unconnect_times_30d,
    t1.electricity_amt_3m,
    t4.fail_txn_cnt_180d_v2,
    t2.max_paid_total_60d_ratio_prev_t79,
    t3.press_30d_all,
    t4.payee_recent_360_payer_share_30d_v2,
    t11.growth_rate_cashbox_7days,
    t5.dpd_due365d_dpd3_bad_eli_rt,
    t1.cat_tools_avg_install_days,
    t4.transfer_fail_ratio_180d_v2,
    t1.same_device_info_differ_regmobile_total_cnt,
    t3.ratio_press_cur60_prev60_all,
    t4.payer_low_mcht_amt_share_180d_v2,
    t1.longitude_latitude_sx_succ_cnt_1d,
    t4.payer_low_mcht_amt_share_15d_v2,
    t4.payee_amount_cv_180d_v2,
    t4.payee_avg_txn_per_payer_shift_7d_vs_180d_v2,
    t4.payee_low_mcht_amt_share_180d_v2,
    t4.payee_recent_180_payer_share_7d_v2,
    t1.balance_pay_cnt,
    t5.dpd_due365d_dpd2_bad_eli_rt,
    t4.transfer_fail_ratio_60d_v2,
    t1.ng_flexi_last_settlement_days_off,
    t1.ng_loan_continue_reject_cnt5,
    t1.gps_city,
    t4.transfer_fail_cnt_360d_v2,
    t1.ins_max_available_term,
    t1.kyc_tier,
    t9.blacklist_cnt_180d,
    t10.blacklist_cnt_180d as blacklist_cnt_180d_v1,
    t9.bvn_cnt_30d_div_90d,
    t4.payee_low_mcht_cnt_90d_v2,
    t6.last_util_1_t9,
    t6.avg_util_90d_all,
    t2.avg_diff_days_90d_t79,
    t4.payee_amount_cv_60d_v2,
    t4.payer_unknown_bank_amt_share_360d_v2,
    t5.dpd_due365d_dpd3_bad_due_rt,
    t4.payee_txn_per_day_30d_v2,
    t6.avg_util_15d_all,
    t4.payee_recent_360_payer_share_15d_v2,
    t4.payer_low_mcht_amt_share_60d_v2,
    t4.payee_avg_txn_per_payer_90d_v2,
    t6.util_90d_sumratio_t9,
    t4.payee_success_rate_60d_v2,
    t2.avg_diff_days_30d_t79,
    t12.avg_tenor_60d_all,
    t6.max_util_15d_t7,
    t4.payee_fail_rate_90d_v2,
    t4.payee_low_mcht_amt_share_30d_v2,
    t4.payer_low_mcht_amt_share_90d_v2,
    t1.databundle_airtime_cnt_1m,
    t8.first_overdue_gap_from_first_loan_days_79,
    t4.fail_txn_cnt_360d_v2,
    t2.avg_diff_days_90d_t9,
    t5.dpd_due180d_dpd4_bad_eli_rt,
    t1.longitude_latitude_sx_succ_cnt_7d,
    t1.pp_trans_cnt_7d,
    t1.same_inflow_payer_union_other_new_pp_acct_cnt_30d,
    t4.payer_amount_cv_180d_v2,
    t6.std_util_180d_all,
    t12.avg_tenor_90d_all,
    t8.max_od_days_60d_9,
    t1.if_af_reject,
    t3.press_15d_all,
    t4.avg_savings_rate_3m_v2,
    t1.ng_compare_target_img_matches_similarity_zy_rt,
    t8.last1_od_days_9,
    t4.payer_amount_cv_7d_v2,
    t1.cash_his_repay_cnt,
    t4.payee_avg_txn_per_payer_180d_v2,
    t4.payee_amount_cv_30d_v2,
    t9.multi_data_cnt_30d_div_90d,
    t1.ng_la30ds_quota_use_ratio_cash_min_off,
    t6.util_180d_sumratio_t9,
    t4.savings_rate_t1_v2,
    t5.dpd_due180d_dpd3_bad_eli_rt,
    t2.active_ratio_due_180d_t79,
    t2.avg_diff_days_60d_t7,
    t6.min_util_180d_t9,
    t3.ratio_press_cur90_prev90_all,
    t12.max_tenor_60d_all,
    t1.cnt_apply_30d_type7,
    t8.last1_od_days_7,
    t8.first_overdue_gap_from_first_loan_days_7,
    t4.payer_amount_cv_90d_v2,
    t6.first_util_1_all,
    t3.ratio_press_cur15_prev15_all,
    t4.payer_amount_cv_30d_v2,
    t2.repay_pay_cnt_180d_t79,
    t8.last_overdue_gap_to_asof_days_7,
    t4.repay_to_topup_ratio_360d_v2,
    t4.payer_amount_cv_60d_v2,
    t1.ng_ins_period_use_ratio,
    t5.dpd_due_latest_dpd1_bad_eli_rt,
    t1.cash_increase_cnt_last_30d,
    t3.ratio_press_cur7_prev7_all,
    t6.last_util_1_t7,
    t5.dpd_due_latest_dpd1_bad_due_rt,
    t2.ontime_settle_loan_cnt_180d_t79,
    t1.total_finsave_amt_20w_days_d30,
    t1.ins_last_loan_term,
    t6.first_util_3_t9,
    t1.installment_period_ratio_last5_orders,
    t1.available_balance_total,
    t1.payer_amount_median_180d_v2,
    t1.ng_la30ds_bi_paid_penalty_cash_avg_off,
    t1.cash_settle_loan_cnt,
    t1.curr_loan_terms,
    t4.payer_repay_cnt_360d_v2 as payer_repay_cnt_360d_v2_v1,
    t12.avg_tenor_180d_all,
    t1.max_paid_interest_180d_t7,
    t4.payer_repay_cnt_60d_v2,
    t11.avg_balance_all_7days,
    t1.ng_cash_overdue_7d_ratio,
    t1.p20_total_finsave_amt_d60,
    t1.ng_same_bvn_card_no_overduedays_ins,
    t1.ng_cash_total_jy_months_off,
    t1.cust_last1_overdue_days,
    t11.diff_balance_targetsaving_7days,
    t1.max_trans_amt_3m,
    t1.transfer_amt_1m_2m,
    t1.ng_cash_success_loan_cnt_d7,
    t1.total_pay_50_rate,
    t5.fpd_loan180d_dpd1_eli_rt,
    t1.flexi_last2_max_overdue_days,
    t1.longitude,
    t4.payee_recent_360_txn_share_15d_v2,
    t1.ng_la3times_bi_overdue_ds_cash_avg_rt,
    t4.transfer_fail_ratio_90d_v2,
    t4.payee_success_rate_360d_v2,
    t1.loan_period_days,
    t11.user_tenure_days,
    t4.payee_recent_180_txn_share_15d_v2,
    t5.dpd_due90d_dpd3_bad_due_rt,
    t1.airtime_amt_3m,
    t4.payee_recent_180_txn_share_90d_v2,
    t1.card_pay_cnt,
    t4.loan_net_inflow_30d_v2,
    t4.payer_recent_180_txn_share_90d_v2,
    t4.fail_txn_ratio_60d_v2,
    t1.trans_mon_rate,
    t9.bank_cnt_180d,
    t10.bank_cnt_180d as bank_cnt_180d_v1,
    t1.databundle_airtime_amt_2m_3m,
    t4.payer_success_rate_30d_v2,
    t4.payer_success_rate_7d_v2,
    t3.press_over_quota_180d_t7,
    t4.max_income_day_std_3m_v2,
    t4.payee_amount_cv_15d_v2,
    t11.ss_auto_dep_last_days,
    t1.ca1_last2_bill_max_overdue_days,
    t4.payee_success_rate_7d_v2,
    t1.flexi_apply_last1_sx_days,
    t1.max_total_finsave_amt_d30,
    t3.press_over_quota_30d_all,
    t4.payee_success_rate_90d_v2,
    t5.dpd_due180d_dpd8_bad_eli_rt,
    t2.repay_ratio_due_90d_t7,
    t11.diff_balance_spendsave_30days,
    t6.min_util_180d_t7,
    t4.payee_recent_180_txn_share_30d_v2,
    t4.payer_start_of_month_amount_ratio_30d_v2,
    t12.avg_tenor_180d_t7,
    t5.dpd_due365d_dpd1_bad_due_rt,
    t8.last3_od_days_7,
    t1.cash_last3_bill_max_overdue_days,
    t4.payer_recent_360_txn_share_60d_v2,
    t1.payee_start_of_month_amount_ratio_180d,
    t5.dpd_due365d_dpd4_bad_eli_rt,
    t2.avg_diff_days_90d_t7,
    t4.payer_low_mcht_cnt_360d_v2,
    t4.payee_recent_180_txn_share_60d_v2,
    t4.payee_recent_360_txn_share_60d_v2,
    t11.diff_balance_all_1day,
    t11.cb_auto_dep_rat_amt_7d_life,
    t11.cb_dep_fail_life_cnt,
    t4.fail_txn_cnt_60d_v2,
    t4.payee_weekend_txn_count_ratio_90d_v2,
    t4.fail_txn_ratio_30d_v2,
    t1.jy_last_bankcard_days,
    t1.max_cur_overdue_day_for_loan,
    t1.ng_indepcash_curday_succ_order_user,
    t4.payer_recent_180_txn_share_60d_v2,
    t4.payee_start_of_month_amount_ratio_360d_v2,
    t4.payer_fail_rate_90d_v2,
    t7.days_reg_to_first_apply_type9,
    t1.p50_total_finsave_amt_d30,
    t1.ins_days_from_last_ser_incresed,
    t1.okcard_jy_cnt,
    t1.avg_last_rnk3_use_rate,
    t1.total_coupon_cnt_rate,
    t4.payee_low_mcht_amt_share_15d_v2,
    t8.last2_od_days_7,
    t3.press_over_quota_prev90d_all,
    t1.ng_cash_cycle_ratio_off,
    t4.payee_unknown_bank_cnt_15d_v2,
    t1.avg_balance_amt_d90,
    t4.payer_recent_180_payee_share_15d_v2,
    t11.cb_auto_dep_90d_cnt,
    t4.payer_recent_360_amount_share_180d_v2,
    t4.payee_eom_amount_ratio_90d_v2,
    t11.sum_total_earnings,
    t4.payee_recent_360_amount_share_180d_v2,
    t1.pp_trans_cnt_3d,
    t4.payee_recent_180_payer_share_180d_v2,
    t4.payer_transfer_top1_amt_share_90d_v2,
    t4.payer_recent_360_payee_share_30d_v2,
    t2.avg_diff_days_180d_t7,
    t4.transfer_fail_ratio_30d_v2,
    t1.cash_bill_cnt,
    t11.cb_auto_dep_rat_amt_30d_life,
    t1.longitude_latitude_apply_cnt_1d,
    t4.payer_recent_360_txn_share_180d_v2,
    t11.cb_withdraw_last_days,
    t4.payer_end_of_month_txn_count_ratio_30d_v2,
    t11.cb_auto_dep_life_cnt,
    t11.cb_auto_dep_rat_cnt_90d_life,
    t11.cb_auto_dep_rat_amt_180d_life,
    t4.payer_eom_amount_ratio_60d_v2,
    t4.payer_end_of_month_txn_count_ratio_90d_v2,
    t4.payer_transfer_top1_amt_share_30d_v2,
    t1.ng_appname_drive_dd,
    t2.max_paid_interest_30d_ratio_prev_t79,
    t4.payer_amount_cv_15d_v2,
    t4.payee_fail_rate_30d_v2,
    t4.payer_night_txn_ratio_shift_30d_vs_180d_v2,
    t4.transfer_fail_ratio_15d_v2,
    t1.build_board,
    t4.payee_start_of_month_amount_ratio_180d_v2,
    t4.payee_recent_360_payer_share_60d_v2,
    t11.growth_rate_cashbox_15days,
    t4.payer_eom_amount_ratio_360d_v2,
    t4.payer_counterparty_hhi_7d_v2,
    t4.payer_low_mcht_cnt_90d_v2,
    t2.deduct_ratio_due_90d_t79,
    t1.coupon_cnt,
    t11.ss_withdraw_life_cnt,
    t1.user_first_quota,
    t1.cash_avg_loantime_term_rnk10,
    t4.payer_weekend_amount_sum_ratio_180d_v2,
    t1.avg_balance_amt_d60,
    t11.cb_auto_dep_fail_life_ratio,
    t1.disk_free_total_space,
    t11.ratio_balance_fixedsaving_all,
    t11.smartearn_days_since_first_deposit,
    t4.payee_recent_360_amount_share_15d_v2,
    t4.payer_eom_amount_ratio_30d_v2,
    t1.payer_avg_txn_per_payee_shift_7d_vs_180d,
    t2.active_ratio_due_180d_t7,
    t1.cash_his_active_repay_cnt,
    t11.cb_auto_dep_60d_cnt,
    t1.databundle_airtime_amt_1m_2m,
    t3.ratio_press_cur90_prev90_t7,
    t11.cb_auto_dep_rat_cnt_180d_life,
    t4.payee_amount_cv_7d_v2,
    t11.growth_rate_cashbox_30days,
    t4.payee_night_txn_ratio_shift_30d_vs_180d_v2,
    t1.ng_same_longitude_order_user_l3d_off,
    t2.max_paid_interest_60d_ratio_prev_t79,
    t4.payer_avg_txn_per_payee_shift_7d_vs_180d_v2,
    t1.payer_txn_count_weekend_360d_v2,
    t11.ratio_global_coverage_60d,
    t1.ng_same_latitude_apply_user_l3d_off,
    t4.payee_eom_amount_ratio_360d_v2,
    t4.avg_repay_amt_3m_v2,
    t1.payee_avg_txn_per_payer_60d,
    t4.payee_weekend_txn_count_ratio_360d_v2,
    t6.cv_util_180d_t7,
    t1.ng_pdlcash_new_curday_succ_order,
    t1.payee_avg_txn_per_payer_shift_7d_vs_180d,
    t4.payee_weekend_amount_sum_ratio_90d_v2,
    t4.payee_recent_360_amount_share_60d_v2,
    t4.payer_transfer_top1_amt_share_15d_v2,
    t4.payer_avg_txn_per_payee_30d_v2,
    t4.payee_counterparty_hhi_180d_v2,
    t2.max_paid_interest_90d_ratio_prev_t7,
    t4.payer_counterparty_hhi_15d_v2,
    t1.app_num,
    t2.avg_diff_days_30d_t7,
    t1.jy_last_bvn_days,
    t4.payee_weekend_txn_count_ratio_180d_v2,
    t11.growth_rate_cashbox_1day,
    t4.payer_transfer_top1_amt_share_180d_v2,
    t4.payer_recent_360_amount_share_7d_v2,
    t1.ng_pdlcash_curday_succ_order,
    t4.payer_night_txn_count_ratio_360d_v2,
    t4.payee_transfer_top1_amt_share_360d_v2,
    t1.ng_applist_small_1000_b_cnt_days_update_mean_rt,
    t1.cal_first_credit_use_rate,
    t1.ng_total_coupon_amt_rate_3d,
    t4.payee_night_amount_sum_ratio_360d_v2,
    t1.total_pay_0_rate,
    t4.payer_amount_median_360d_v2,
    t1.transfer_amt_1m,
    t1.ng_applist_small_1000_b_cnt_90_days_update_sum_rt,
    t1.trans_amt_7d,
    t1.loyalty_amt,
    t1.days_between_openaccount_and_excute,
    t1.transfer_cnt_7d,
    t4.payer_fail_rate_360d_v2,
    t1.databundle_cnt_3m,
    t7.days_reg_to_first_apply_type79,
    t1.max_id_authen_days,
    t4.payee_avg_txn_per_payer_60d_v2,
    t11.cb_dep_life_avg,
    t1.member_num,
    t1.stragety_to_ins_test_group,
    t1.screen_brightness,
    t1.phone_electric_quantity,
    t1.gender,
    t1.app350_install_days,
    t1.min_total_finsave_amt_d90,
    t1.build_host,
    t1.min_verify_days,
    t1.same_device_info_differ_regmobile_last15_cnt_plampay,
    t1.same_device_info_apply_total_times,
    t1.ng_applist_small_1000_b_ratio10_days_update_min_rt,
    t4.payer_avg_txn_per_payee_360d_v2,
    t4.payer_success_rate_360d_v2,
    t1.same_device_info_apply_last30_times,
    t4.payer_fail_rate_60d_v2,
    t1.ng_nin_cnt_off,
    t1.pp_kyc_state_name,
    t1.ng_last_bill_max_overdue_days_off,
    t4.payer_night_txn_count_ratio_180d_v2,
    t4.payer_counterparty_hhi_360d_v2,
    t4.payer_txn_count_360d_v2,
    t4.fail_txn_ratio_180d_v2,
    t1.phone_brand,
    t1.same_full_name_differ_cnt_3d,
    t1.ng_appname_okash_dd,
    t4.payee_start_of_month_amount_ratio_90d_v2,
    t4.payer_avg_txn_per_payee_shift_7d_vs_360d_v2,
    t4.payer_transfer_top1_amt_share_360d_v2,
    t1.ng_collect_cuiji_unconnect_times_20d,
    t11.diff_balance_targetsaving_1day,
    t4.payee_low_mcht_amt_7d_v2,
    t4.payee_eom_amount_ratio_15d_v2,
    t4.payee_txn_per_day_60d_v2,
    t4.payer_recent_180_txn_share_7d_v2,
    t4.payee_txn_per_day_90d_v2,
    t11.sum_total_interest,
    t4.payee_unknown_bank_cnt_share_180d_v2,
    t4.payer_txn_per_day_180d_v2,
    t1.airtime_cnt_3m,
    t4.payee_weekend_amount_sum_ratio_15d_v2,
    t4.payee_recent_180_amount_share_7d_v2,
    t4.payer_fee_cnt_360d_v2,
    t1.ng_current_max_overdue_days_off,
    t4.payee_low_mcht_amt_share_60d_v2,
    t4.cashout_to_inflow_ratio_360d_v2,
    t4.payer_recent_360_payee_share_15d_v2,
    t4.payer_recent_360_payee_share_7d_v2
from sample_table as t

-- t1: pb_ads_credit.direct_send_in_out_para_data_df，获取特征字段数: 255
left join (
    select cid, pt, loan_total_fee, loan_total_interest, loan_interest_days, latitude, app_version, age, loan_interest_rate, user_withdrawal_ratio_now, reg_day, n_loan_period_days, usr_overdue_days_max, ng_pp_total_balance_off, pp_max_nibssfund_amt_3d, max_trans_amt_1m, cust_curr_overdue_bill_amt, c_first_3dig_bvn, pp_payoff_cnt, other_self_airtime_cnts, bus_pp_30d_aum, loan_penalty_rate, one_period_days, ng_ins_increase_currd_total_amt, cash_cur_day_ser_increase_cnt, loan_cust_account_status, pp_trans_amt_7d, pp_register_software, avg_balance_when_gt_0_90d, max_trans_amt_6m, available_balance_pp, pp_nibssfund_amt_3d, payer_repay_cnt_360d_v2, num_device_count, ng_same_nin_max_cur_overdue_day_cash_rt, total_storage, ng_cash_success_loan_cnt_d3, transfer_cnt_1m, databundle_airtime_amt_1m, ng_cash_settle_ratio, trans_days_60d, if_register_palmpay_device, ng_cash_withdraw_jy_reject_cnt, cash_days_from_last_incresed, ng_applist_pkgname_last_30_day_pd3_best5_cnt, ng_cash_success_loan_cnt_d14, max_authen_days, p20_total_finsave_amt_d30, total_vat_7d, n_cust_max_overdue_days, ins_max_cur_overdue_day_for_loan, ng_cash_loan_cnt_7d, pp_last_reg_days, hours_since_last_launch, other_airtime_cnt, cust_last_market_increase_days, pp_trans_days_14d, phone_model, ratio_install_90d, ng_ins_reg_sx_days, min_authen_days, pc_counter_sx_curday_succ_cnt, ng_collect_cuiji_ptp_times_30d, ng_total_loyalty_cnt_rate, total_memory, transfer_cnt_3m, c_gender, installment_loan_rank, self_airtime_vat, ng_appname_opay_dd, ng_loan_continue_reject_cnt3, max_continue_days, ng_max_trans_amt, self_airtime_vat_60d, pp_register_second_channel, app38_install_days, total_daily_vat_14d, trans_days_cnt, max_verify_days, coupon_amt, ng_pp_regular_trans_order_cnt_60d_off, okcard_last3_max_overdue_days, user_recent_overdue_day, pp_trans_amt_3d, ng_applist_small_1000_b_ratio10_90_days_update_sum_rt, app55_install_days, inst_cnt_30d, payer_repay_cnt_30d, databundle_amt_3m, ng_applist_pkgname_last_30_day_pd3_worst5_cnt, credit_day, nibssfund_cnt_7d, sdcard_used_capacity_rate, pp_kyc_profession, total_balance_pay_amt_rate, same_device_info_differ_regmobile_last30_cnt_plampay, cus_all_product_curr_overdue_cnt, ng_same_bvn_max_cur_overdue_day_cash_rt, ng_td_witld_amt_in_bi_rt, cust_last2_overdue_days, trans_cnt, ng_pdl_is_first_order, ng_la3times_quota_use_ratio_cash_avg_rt, withdraw_apply_total_cnt, cust_tier, min_pass_verify_days, n_cust_last1_overdue_days, ng_same_ipaddress_card_cnt_cash_rt, same_device_info_differ_regmobile_total_cnt_plampay, ng_cash_total_duedate_repay_cnt_rt, ng_faceid_max_overdue_days_emi, p80_total_finsave_amt_d90, pay_100up_cnt, num_connect_user_device, num_device_log_7day, phone_system, ng_applist_small_1000_b_ratio10_30_days_update_sum_rt, approval_result1, pp_nibssfund_days_3d, total_performing_facility_ratio, p50_balance_amt_d30, phone_width, bus_application_gps_address_detail, total_daily_vam_3d, same_bvn_curr_overdue_days, trans_amt_3d, same_device_info_differ_regmobile_last30_cnt, betting_customer_id_pp_count, ng_nin_age_rt, used_memory, max_continue_days_6m, stragety_flag_ser, ng_pp_regular_trans_order_cnt_3d_off, card_pay_days, cash_jy_curr_day_cnt, ng_la360ds_bi_overdue_ds_cash_avg_off, flag_offline_limit_adjust, wifi_conneted, ng_collect_cuiji_unconnect_times_30d, electricity_amt_3m, cat_tools_avg_install_days, same_device_info_differ_regmobile_total_cnt, longitude_latitude_sx_succ_cnt_1d, balance_pay_cnt, ng_flexi_last_settlement_days_off, ng_loan_continue_reject_cnt5, gps_city, ins_max_available_term, kyc_tier, databundle_airtime_cnt_1m, longitude_latitude_sx_succ_cnt_7d, pp_trans_cnt_7d, same_inflow_payer_union_other_new_pp_acct_cnt_30d, if_af_reject, ng_compare_target_img_matches_similarity_zy_rt, cash_his_repay_cnt, ng_la30ds_quota_use_ratio_cash_min_off, cnt_apply_30d_type7, ng_ins_period_use_ratio, cash_increase_cnt_last_30d, total_finsave_amt_20w_days_d30, ins_last_loan_term, installment_period_ratio_last5_orders, available_balance_total, payer_amount_median_180d_v2, ng_la30ds_bi_paid_penalty_cash_avg_off, cash_settle_loan_cnt, curr_loan_terms, max_paid_interest_180d_t7, ng_cash_overdue_7d_ratio, p20_total_finsave_amt_d60, ng_same_bvn_card_no_overduedays_ins, ng_cash_total_jy_months_off, cust_last1_overdue_days, max_trans_amt_3m, transfer_amt_1m_2m, ng_cash_success_loan_cnt_d7, total_pay_50_rate, flexi_last2_max_overdue_days, longitude, ng_la3times_bi_overdue_ds_cash_avg_rt, loan_period_days, airtime_amt_3m, card_pay_cnt, trans_mon_rate, databundle_airtime_amt_2m_3m, ca1_last2_bill_max_overdue_days, flexi_apply_last1_sx_days, max_total_finsave_amt_d30, cash_last3_bill_max_overdue_days, payee_start_of_month_amount_ratio_180d, jy_last_bankcard_days, max_cur_overdue_day_for_loan, ng_indepcash_curday_succ_order_user, p50_total_finsave_amt_d30, ins_days_from_last_ser_incresed, okcard_jy_cnt, avg_last_rnk3_use_rate, total_coupon_cnt_rate, ng_cash_cycle_ratio_off, avg_balance_amt_d90, pp_trans_cnt_3d, cash_bill_cnt, longitude_latitude_apply_cnt_1d, ng_appname_drive_dd, build_board, coupon_cnt, user_first_quota, cash_avg_loantime_term_rnk10, avg_balance_amt_d60, disk_free_total_space, payer_avg_txn_per_payee_shift_7d_vs_180d, cash_his_active_repay_cnt, databundle_airtime_amt_1m_2m, ng_same_longitude_order_user_l3d_off, payer_txn_count_weekend_360d_v2, ng_same_latitude_apply_user_l3d_off, payee_avg_txn_per_payer_60d, ng_pdlcash_new_curday_succ_order, payee_avg_txn_per_payer_shift_7d_vs_180d, app_num, jy_last_bvn_days, ng_pdlcash_curday_succ_order, ng_applist_small_1000_b_cnt_days_update_mean_rt, cal_first_credit_use_rate, ng_total_coupon_amt_rate_3d, total_pay_0_rate, transfer_amt_1m, ng_applist_small_1000_b_cnt_90_days_update_sum_rt, trans_amt_7d, loyalty_amt, days_between_openaccount_and_excute, transfer_cnt_7d, databundle_cnt_3m, max_id_authen_days, member_num, stragety_to_ins_test_group, screen_brightness, phone_electric_quantity, gender, app350_install_days, min_total_finsave_amt_d90, build_host, min_verify_days, same_device_info_differ_regmobile_last15_cnt_plampay, same_device_info_apply_total_times, ng_applist_small_1000_b_ratio10_days_update_min_rt, same_device_info_apply_last30_times, ng_nin_cnt_off, pp_kyc_state_name, ng_last_bill_max_overdue_days_off, phone_brand, same_full_name_differ_cnt_3d, ng_appname_okash_dd, ng_collect_cuiji_unconnect_times_20d, airtime_cnt_3m, ng_current_max_overdue_days_off
    from pb_ads_credit.direct_send_in_out_para_data_df
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t1 on t.pt_sub1d = t1.pt and t.cid = t1.cid

-- t2: pb_biz_credit.keep_jch_ng_cid_repay_feature_final，获取特征字段数: 24
left join (
    select cid, pt, max_paid_interest_180d_t79, deduct_ratio_due_180d_t79, max_paid_interest_90d_ratio_prev_t79, repay_ratio_due_60d_t79, early_ratio_due_180d_t79, avg_diff_days_180d_t79, repay_ratio_due_180d_t79, max_paid_total_60d_ratio_prev_t79, avg_diff_days_90d_t79, avg_diff_days_30d_t79, avg_diff_days_90d_t9, active_ratio_due_180d_t79, avg_diff_days_60d_t7, repay_pay_cnt_180d_t79, ontime_settle_loan_cnt_180d_t79, repay_ratio_due_90d_t7, avg_diff_days_90d_t7, avg_diff_days_180d_t7, max_paid_interest_30d_ratio_prev_t79, deduct_ratio_due_90d_t79, active_ratio_due_180d_t7, max_paid_interest_60d_ratio_prev_t79, max_paid_interest_90d_ratio_prev_t7, avg_diff_days_30d_t7
    from pb_biz_credit.keep_jch_ng_cid_repay_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t2 on t.pt_sub1d = t2.pt and t.cid = t2.cid

-- t3: pb_biz_credit.keep_jch_ng_cid_bal_feature_final，获取特征字段数: 23
left join (
    select cid, pt, press_180d_all, press_90d_all, press_15d_t9, press_prev90d_all, press_60d_all, press_over_quota_180d_all, press_180d_t7, press_30d_t9, press_180d_t9, press_90d_t7, press_7d_all, press_over_quota_90d_all, ratio_press_cur30_prev30_all, press_30d_all, ratio_press_cur60_prev60_all, press_15d_all, ratio_press_cur90_prev90_all, ratio_press_cur15_prev15_all, ratio_press_cur7_prev7_all, press_over_quota_180d_t7, press_over_quota_30d_all, press_over_quota_prev90d_all, ratio_press_cur90_prev90_t7
    from pb_biz_credit.keep_jch_ng_cid_bal_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t3 on t.pt_sub1d = t3.pt and t.cid = t3.cid

-- t4: pb_ads_credit.ads_ng_risk_pp_cid_character_360d，获取特征字段数: 181
left join (
    select cid, pt, payer_amount_median_60d_v2, loan_net_inflow_90d_v2, loan_net_inflow_60d_v2, payer_amount_median_15d_v2, payee_txn_per_day_360d_v2, payee_unique_payer_count_7d_v2, payer_txn_per_day_360d_v2, payer_low_mcht_amt_share_360d_v2, payee_txn_per_day_180d_v2, payee_recent_180_amount_share_15d_v2, fail_txn_ratio_360d_v2, payer_success_rate_60d_v2, payee_recent_360_txn_share_7d_v2, payee_recent_180_payer_share_30d_v2, payee_low_mcht_amt_share_360d_v2, fail_txn_ratio_90d_v2, payee_fail_rate_360d_v2, payer_unique_payee_count_180d_v2, payee_avg_txn_per_payer_360d_v2, payee_high_mcht_amt_share_360d_v2, transfer_fail_ratio_360d_v2, payee_amount_cv_360d_v2, payee_unique_hours_active_7d_v2, payer_recent_180_amount_share_90d_v2, payee_recent_360_payer_share_7d_v2, payee_unique_hours_active_15d_v2, short_cycle_inflow_ratio_t1_v2, payee_unique_payer_count_360d_v2, payee_avg_txn_per_payer_shift_7d_vs_360d_v2, payee_txn_per_day_15d_v2, payer_start_of_month_amount_ratio_360d_v2, payer_recent_360_txn_share_7d_v2, fail_txn_ratio_15d_v2, payee_success_rate_180d_v2, payer_unique_payee_count_60d_v2, payer_repay_cnt_15d_v2, payee_start_of_month_amount_ratio_30d_v2, payee_recent_180_payer_share_15d_v2, payer_recent_180_amount_share_7d_v2, payer_unique_payee_count_360d_v2, payee_eom_amount_ratio_30d_v2, payer_repay_cnt_180d_v2, payer_amount_cv_360d_v2, payer_repay_cnt_30d_v2, payer_low_mcht_amt_share_30d_v2, payee_recent_180_payer_share_90d_v2, payee_recent_180_payer_share_60d_v2, payee_amount_cv_90d_v2, fail_txn_cnt_180d_v2, payee_recent_360_payer_share_30d_v2, transfer_fail_ratio_180d_v2, payer_low_mcht_amt_share_180d_v2, payer_low_mcht_amt_share_15d_v2, payee_amount_cv_180d_v2, payee_avg_txn_per_payer_shift_7d_vs_180d_v2, payee_low_mcht_amt_share_180d_v2, payee_recent_180_payer_share_7d_v2, transfer_fail_ratio_60d_v2, transfer_fail_cnt_360d_v2, payee_low_mcht_cnt_90d_v2, payee_amount_cv_60d_v2, payer_unknown_bank_amt_share_360d_v2, payee_txn_per_day_30d_v2, payee_recent_360_payer_share_15d_v2, payer_low_mcht_amt_share_60d_v2, payee_avg_txn_per_payer_90d_v2, payee_success_rate_60d_v2, payee_fail_rate_90d_v2, payee_low_mcht_amt_share_30d_v2, payer_low_mcht_amt_share_90d_v2, fail_txn_cnt_360d_v2, payer_amount_cv_180d_v2, avg_savings_rate_3m_v2, payer_amount_cv_7d_v2, payee_avg_txn_per_payer_180d_v2, payee_amount_cv_30d_v2, savings_rate_t1_v2, payer_amount_cv_90d_v2, payer_amount_cv_30d_v2, repay_to_topup_ratio_360d_v2, payer_amount_cv_60d_v2, payer_repay_cnt_360d_v2, payer_repay_cnt_60d_v2, payee_recent_360_txn_share_15d_v2, transfer_fail_ratio_90d_v2, payee_success_rate_360d_v2, payee_recent_180_txn_share_15d_v2, payee_recent_180_txn_share_90d_v2, loan_net_inflow_30d_v2, payer_recent_180_txn_share_90d_v2, fail_txn_ratio_60d_v2, payer_success_rate_30d_v2, payer_success_rate_7d_v2, max_income_day_std_3m_v2, payee_amount_cv_15d_v2, payee_success_rate_7d_v2, payee_success_rate_90d_v2, payee_recent_180_txn_share_30d_v2, payer_start_of_month_amount_ratio_30d_v2, payer_recent_360_txn_share_60d_v2, payer_low_mcht_cnt_360d_v2, payee_recent_180_txn_share_60d_v2, payee_recent_360_txn_share_60d_v2, fail_txn_cnt_60d_v2, payee_weekend_txn_count_ratio_90d_v2, fail_txn_ratio_30d_v2, payer_recent_180_txn_share_60d_v2, payee_start_of_month_amount_ratio_360d_v2, payer_fail_rate_90d_v2, payee_low_mcht_amt_share_15d_v2, payee_unknown_bank_cnt_15d_v2, payer_recent_180_payee_share_15d_v2, payer_recent_360_amount_share_180d_v2, payee_eom_amount_ratio_90d_v2, payee_recent_360_amount_share_180d_v2, payee_recent_180_payer_share_180d_v2, payer_transfer_top1_amt_share_90d_v2, payer_recent_360_payee_share_30d_v2, transfer_fail_ratio_30d_v2, payer_recent_360_txn_share_180d_v2, payer_end_of_month_txn_count_ratio_30d_v2, payer_eom_amount_ratio_60d_v2, payer_end_of_month_txn_count_ratio_90d_v2, payer_transfer_top1_amt_share_30d_v2, payer_amount_cv_15d_v2, payee_fail_rate_30d_v2, payer_night_txn_ratio_shift_30d_vs_180d_v2, transfer_fail_ratio_15d_v2, payee_start_of_month_amount_ratio_180d_v2, payee_recent_360_payer_share_60d_v2, payer_eom_amount_ratio_360d_v2, payer_counterparty_hhi_7d_v2, payer_low_mcht_cnt_90d_v2, payer_weekend_amount_sum_ratio_180d_v2, payee_recent_360_amount_share_15d_v2, payer_eom_amount_ratio_30d_v2, payee_amount_cv_7d_v2, payee_night_txn_ratio_shift_30d_vs_180d_v2, payer_avg_txn_per_payee_shift_7d_vs_180d_v2, payee_eom_amount_ratio_360d_v2, avg_repay_amt_3m_v2, payee_weekend_txn_count_ratio_360d_v2, payee_weekend_amount_sum_ratio_90d_v2, payee_recent_360_amount_share_60d_v2, payer_transfer_top1_amt_share_15d_v2, payer_avg_txn_per_payee_30d_v2, payee_counterparty_hhi_180d_v2, payer_counterparty_hhi_15d_v2, payee_weekend_txn_count_ratio_180d_v2, payer_transfer_top1_amt_share_180d_v2, payer_recent_360_amount_share_7d_v2, payer_night_txn_count_ratio_360d_v2, payee_transfer_top1_amt_share_360d_v2, payee_night_amount_sum_ratio_360d_v2, payer_amount_median_360d_v2, payer_fail_rate_360d_v2, payee_avg_txn_per_payer_60d_v2, payer_avg_txn_per_payee_360d_v2, payer_success_rate_360d_v2, payer_fail_rate_60d_v2, payer_night_txn_count_ratio_180d_v2, payer_counterparty_hhi_360d_v2, payer_txn_count_360d_v2, fail_txn_ratio_180d_v2, payee_start_of_month_amount_ratio_90d_v2, payer_avg_txn_per_payee_shift_7d_vs_360d_v2, payer_transfer_top1_amt_share_360d_v2, payee_low_mcht_amt_7d_v2, payee_eom_amount_ratio_15d_v2, payee_txn_per_day_60d_v2, payer_recent_180_txn_share_7d_v2, payee_txn_per_day_90d_v2, payee_unknown_bank_cnt_share_180d_v2, payer_txn_per_day_180d_v2, payee_weekend_amount_sum_ratio_15d_v2, payee_recent_180_amount_share_7d_v2, payer_fee_cnt_360d_v2, payee_low_mcht_amt_share_60d_v2, cashout_to_inflow_ratio_360d_v2, payer_recent_360_payee_share_15d_v2, payer_recent_360_payee_share_7d_v2
    from pb_ads_credit.ads_ng_risk_pp_cid_character_360d
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t4 on t.pt_sub1d = t4.pt and t.cid = t4.cid

-- t5: pb_biz_credit.ng_customer_pay_plan_flow_feas，获取特征字段数: 19
left join (
    select cid, pt, last_initiative_pay_days, first_initiative_pay_days, last_pay_days, first_pay_days, dpd_due365d_dpd2_bad_due_rt, dpd_due365d_dpd4_bad_due_rt, dpd_due365d_dpd8_bad_eli_rt, dpd_due365d_dpd3_bad_eli_rt, dpd_due365d_dpd2_bad_eli_rt, dpd_due365d_dpd3_bad_due_rt, dpd_due180d_dpd4_bad_eli_rt, dpd_due180d_dpd3_bad_eli_rt, dpd_due_latest_dpd1_bad_eli_rt, dpd_due_latest_dpd1_bad_due_rt, fpd_loan180d_dpd1_eli_rt, dpd_due90d_dpd3_bad_due_rt, dpd_due180d_dpd8_bad_eli_rt, dpd_due365d_dpd1_bad_due_rt, dpd_due365d_dpd4_bad_eli_rt
    from pb_biz_credit.ng_customer_pay_plan_flow_feas
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t5 on t.pt_sub1d = t5.pt and t.cid = t5.cid

-- t6: pb_biz_credit.keep_jch_ng_cid_util_feature_final，获取特征字段数: 22
left join (
    select cid, pt, cv_util_180d_all, last_util_1_all, util_180d_sumratio_all, avg_util_180d_all, min_util_180d_all, util_90d_sumratio_all, max_util_7d_all, cv_util_30d_all, min_util_7d_all, last_util_1_t9, avg_util_90d_all, avg_util_15d_all, util_90d_sumratio_t9, max_util_15d_t7, std_util_180d_all, util_180d_sumratio_t9, min_util_180d_t9, first_util_1_all, last_util_1_t7, first_util_3_t9, min_util_180d_t7, cv_util_180d_t7
    from pb_biz_credit.keep_jch_ng_cid_util_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t6 on t.pt_sub1d = t6.pt and t.cid = t6.cid

-- t7: pb_biz_credit.keep_jch_ng_cid_apply_feature_final，获取特征字段数: 9
left join (
    select cid, pt, days_since_registration, days_since_last_apply_type9, days_since_first_apply_all, days_since_last_apply_all, days_since_first_apply_type9, days_since_last_apply_type7, concat_last_most_type_30d, days_reg_to_first_apply_type9, days_reg_to_first_apply_type79
    from pb_biz_credit.keep_jch_ng_cid_apply_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t7 on t.pt_sub1d = t7.pt and t.cid = t7.cid

-- t8: pb_biz_credit.keep_ng_jch_cid_overdue_feature_final，获取特征字段数: 16
left join (
    select cid, pt, max_od_days_180d_79, last_overdue_gap_to_asof_days_79, max_od_days_30d_79, max_od_days_90d_79, last1_od_days_79, max_od_days_60d_79, last3_od_days_79, last2_od_days_79, first_overdue_gap_from_first_loan_days_79, max_od_days_60d_9, last1_od_days_9, last1_od_days_7, first_overdue_gap_from_first_loan_days_7, last_overdue_gap_to_asof_days_7, last3_od_days_7, last2_od_days_7
    from pb_biz_credit.keep_ng_jch_cid_overdue_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t8 on t.pt_sub1d = t8.pt and t.cid = t8.cid

-- t9: pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final，获取特征字段数: 7
left join (
    select cid, pt, bank_cnt_90d, top1_inst_query_ratio_180d, bvn_cnt_15d_div_90d, blacklist_cnt_180d, bvn_cnt_30d_div_90d, multi_data_cnt_30d_div_90d, bank_cnt_180d
    from pb_biz_credit.keep_jch_ng_cid_multi_loan_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t9 on t.pt_sub1d = t9.pt and t.cid = t9.cid

-- t10: pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature，获取特征字段数: 4
left join (
    select cid, pt, bank_cnt_90d, top1_inst_query_ratio_180d, blacklist_cnt_180d, bank_cnt_180d
    from pb_biz_credit.keep_ng_jch_bvn_nin_phn_multi_loan_feature
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t10 on t.pt_sub1d = t10.pt and t.cid = t10.cid

-- t11: pb_biz_credit.ng_pp_user_financial_feature_profile_di，获取特征字段数: 33
left join (
    select cid, pt, ratio_balance_cashbox_all, sum_balance_cashbox, diff_balance_all_15days, diff_balance_all_30days, growth_rate_cashbox_7days, avg_balance_all_7days, diff_balance_targetsaving_7days, user_tenure_days, ss_auto_dep_last_days, diff_balance_spendsave_30days, diff_balance_all_1day, cb_auto_dep_rat_amt_7d_life, cb_dep_fail_life_cnt, cb_auto_dep_90d_cnt, sum_total_earnings, cb_auto_dep_rat_amt_30d_life, cb_withdraw_last_days, cb_auto_dep_life_cnt, cb_auto_dep_rat_cnt_90d_life, cb_auto_dep_rat_amt_180d_life, growth_rate_cashbox_15days, ss_withdraw_life_cnt, cb_auto_dep_fail_life_ratio, ratio_balance_fixedsaving_all, smartearn_days_since_first_deposit, cb_auto_dep_60d_cnt, cb_auto_dep_rat_cnt_180d_life, growth_rate_cashbox_30days, ratio_global_coverage_60d, growth_rate_cashbox_1day, cb_dep_life_avg, diff_balance_targetsaving_1day, sum_total_interest
    from pb_biz_credit.ng_pp_user_financial_feature_profile_di
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t11 on t.pt_sub1d = t11.pt and t.cid = t11.cid

-- t12: pb_biz_credit.keep_jch_ng_cid_tenor_feature_final，获取特征字段数: 5
left join (
    select cid, pt, avg_tenor_60d_all, avg_tenor_90d_all, max_tenor_60d_all, avg_tenor_180d_all, avg_tenor_180d_t7
    from pb_biz_credit.keep_jch_ng_cid_tenor_feature_final
    where pt >= '${pt_beg}' and pt <= '${pt_end}'
) as t12 on t.pt_sub1d = t12.pt and t.cid = t12.cid
;
